apiVersion: v1
kind: Pod
metadata:
  name: samapp
  annotations:
    iam.amazonaws.com/role: devops-service-role
spec:
  containers:
  - name: samapp
    image: sam0392in/sam:devbox
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
